version: '{build}'

clone_depth: 50

cache:
  - '%LOCALAPPDATA%\Microsoft\dotnet -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\project.json, Nuget.Config'

before_build:
  # Install dotnet cli
  - appveyor DownloadFile https://raw.githubusercontent.com/dotnet/cli/v1.0.4/scripts/obtain/dotnet-install.ps1
  - powershell -File dotnet-install.ps1
  - set PATH=%PATH%;%LOCALAPPDATA%\Microsoft\dotnet
  - dotnet --version

build_script:
  - dotnet build Akka.FtpClient.sln --configuration Release

#test_script:
  #- dotnet test test\

after_test:
  - dotnet pack .\src\Akka.FtpClient\Akka.FtpClient.csproj --configuration=Release --output=".\Nuget"

artifacts:
  - path: .\src\Akka.FtpClient\Nuget\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: BU13VvAuyGHYl0k8Io03XM0T8WiI+2LTnP5WiVIhhxt2qqDh1GtxHg8Vi+bfXBxl
  skip_symbols: false
  artifact: /.*\.nupkg/
  
